name: CI
on: [push, pull_request]

jobs:
  rspec:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deps
        run: |
          apt update && apt install ffmpeg cmake -y
          bundle
      - name: Setup pronto
        run: gem install pronto pronto-rubocop
      - name: Run Pronto
        run: |
          bundle install
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          bundle exec pronto run
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"
          BUNDLE_PATH: vendor/bundle
      - name: RSpec
        run: |
          bundle exec rspec
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          title: Code Coverage Report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
          filter-changed-files: true
          lcov-file: coverage/lcov.info
  lint:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          apt update && apt install cmake -y
          bundle
      - name: Run rubocop
        env:
          DD_ENV: ci
        run: |
          bundle exec rubocop -P
