name: CI
on: [push, pull_request]

jobs:
  rspec:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deps
        run: |
          apt update && apt install ffmpeg cmake -y
          bundle
      - name: RSpec
        run: |
          bundle exec rspec
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          title: Code Coverage Report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
          filter-changed-files: true
          lcov-file: coverage/lcov.info
      - name: Pronto
        if: github.event_name == 'pull_request'
        env:
          PRONTO_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory /__w/rlovelett-ffmpeg/rlovelett-ffmpeg
          # pull origin/master to have a ref to compare against
          git remote set-branches --add origin master
          git fetch
          pronto run -f github_pr_review -c master
  lint:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          apt update && apt install cmake -y
          bundle
      - name: Run rubocop
        env:
          DD_ENV: ci
        run: |
          bundle exec rubocop -P
