name: CI
on: [push, pull_request]

jobs:
  rspec:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deps
        run: |
          apt update && apt install ffmpeg -y
          bundle
      - name: RSpec
        run: |
          bundle exec rspec
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          title: Code Coverage Report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
          filter-changed-files: true
          lcov-file: coverage/lcov.info
      - name: Undercover
        if: github.event_name == 'pull_request'
        run: |
          gem install undercover
          undercover -- compare $GITHUB_BASE_REF
  lint:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          bundle
      - name: Run rubocop
        env:
          DD_ENV: ci
        run: |
          bundle exec rubocop -P
