name: CI
on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deps
        run: |
          echo 'Coveralls token ' + $COVERALLS_REPO_TOKEN
          apt update && apt install ffmpeg -y
          bundle
      - name: RSpec
        run: |
          echo 'rspec Coveralls token ' + $COVERALLS_REPO_TOKEN
          bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          bundle
      - name: Run rubocop
        run: |
          bundle exec rubocop -P
