name: CI
on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          apt update && apt install curl -y
          bundle
      - name: Setup ffmpeg
        run: |
          curl -s -o ffmpeg-arm64.tar.xz "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
          tar -xf ffmpeg-arm64.tar.xz -C /usr/bin/
      - name: RSpec
        run: |
          bundle exec rspec
