name: CI
on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deps
        run: |
          apt update && apt install ffmpeg -y
          bundle
      - name: RSpec
        run: |
          bundle exec rspec
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
  lint:
    runs-on: ubuntu-latest
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          bundle
      - name: Run rubocop
        env:
          DD_ENV: ci
        run: |
          bundle exec rubocop -P
