name: CI
on: push

jobs:
  rspec:
    runs-on: [ubuntu-latest, x64]
    container: public.ecr.aws/docker/library/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          bundle
      - name: RSpec
        run: |
          bundle exec rspec
